telegram_token: "6215166129:AAGAlHHNr6Bpc1kO1yFEt2S0RS8C9sxlB2o"
openai_api_key: "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"
use_chatgpt_api: true
allowed_telegram_usernames: []  # if empty, the bot is available to anyone. pass a username string to allow it and/or user ids as integers
new_dialog_timeout: 600  # new dialog starts after timeout (in seconds)
enable_message_streaming: true  # 流式传输

# 价格
chatgpt_price_per_1000_tokens: 0.002
gpt_price_per_1000_tokens: 0.02
whisper_price_per_1_min: 0.006
