available_text_models: ["gpt-3.5-turbo", "gpt-4", "text-davinci-003"]

info:
  gpt-3.5-turbo:
    type: chat_completion
    name: ChatGPT
    description: ChatGPT模式适用大部分日常使用场景,如果一些情况它无法处理,请把<b>GPT-4</b>叫出来帮忙

    price_per_1000_input_tokens: 0.002
    price_per_1000_output_tokens: 0.002

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  gpt-4:
    type: chat_completion
    name: GPT-4
    description: GPT-4是目前世界上最智能、最先进的型号。但它速度较慢,而且成本效益不如ChatGPT。他是<b>复杂</b>智力任务的最佳选择。

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      Smart: 5
      Fast: 2
      Cheap: 2

  text-davinci-003:
    type: completion
    name: GPT-3.5
    description: 遗留淘汰的备选模型。

    price_per_1000_input_tokens: 0.02
    price_per_1000_output_tokens: 0.02

    scores:
      Smart: 3
      Fast: 2
      Cheap: 3

  whisper:
    type: audio
    price_per_1_min: 0.006